version: "3.8"

services:
  reacher:
    image: reacherhq/backend:latest
    container_name: reacher
    ports:
      - "8085:8080"
    environment:
      - RUST_LOG=info
      - RCH_ENABLE_BULK=true
    restart: always
    networks:
      - dokploy-network 

networks:
  dokploy-network:
    external: true
